### ISSUE TITLE
Build tool to write/update MassBank records to database

### ISSUE THREAD

**Issue by uly55e5** [MassBank/MassBank3#10]
Build a command line tool to create or update the MassBank database from an existing directory containing the MassBank records or from a commit to a MassBank data git repository. The arguments (database connection, source, ...) can be passed by environment variables or command line arguments. 

### Tasks
- [x] create database schema
- [x] create database from MassBank directory
- [x] create database from MassBank-data git repository
- [x] update existing database
- [x] write metadata to database
- [x] read environment variables
- [x] read command line arguments
